### ISSUE TITLE
How to publish to nodejs version

### ISSUE THREAD

**Issue by davidbeijinho** [tiddly-gittly/Modern.TiddlyDev#33]
Hey i was trying to publish a plugin that could be installed in a nodejs plugins folder but was not able to do it

I tried to run

npm run build

and include the generated JSON fike eg `$__plugins_your-name_plugin-name.json ` plus a `plugin.info` file from the src directory but was not able to load the content

**Comment by davidbeijinho** [comment]
for now i have added a new npm run script `npm run publish && tiddlywiki --load ./dist/index.html --savewikifolder ./release` and inside this folder I got the plugins that I can import in nodejs

**Comment by Gk0Wk** [comment]
Hello, I may not have fully understood what you meant. Let me explain my understanding: After building, each json file generated under the dist folder is a separate plugin that can be used independently. You can drag it onto the wiki page of your browser for installation or place it in the tiddlers path of the NodeJS format wiki folder.

**Comment by davidbeijinho** [comment]
you are right, that approach works, i just like to install the plugins in a separated folder in node js like is suggested here https://tiddlywiki.com/#Installing%20custom%20plugins%20on%20Node.js

**Comment by linonetwo** [comment]
> install the plugins in a separate folder in node js

That is deprecated, see https://github.com/Jermolene/TiddlyWiki5/discussions/6096#discussioncomment-1459181

Publish json plugin and use CPL.
