### ISSUE TITLE
Doc：按教程创建ts插件出错，Undefined widget 'RandomNumber'

### ISSUE THREAD

**Issue by zezehihi** [tiddly-gittly/Modern.TiddlyDev#34]
tutorials->TypeScript插件开发->创建一个 Widget->执行` pnpm run dev `对源文件进行编译，打开浏览器，创建一个 tiddler ，在其中使用 `<$RandomNumber />`，可以看到效果。

到这一步时操作出错：Tiddler创建后显示Undefined widget 'RandomNumber'。

测试后发现使用`<$test/>`正确显示RandomNumber Widget的内容。

**Comment by oeyoews** [comment]
应该是教程没有对应上, 最后导出的是test, 可以改为`exports.RandomNumber = ExampleWidget`

**Comment by Zacharia2** [comment]
@Gk0Wk 可以关闭这个issue了，已经解决了。
