### ISSUE TITLE
在TS脚本中导入其他资源时创建该文件的Meta文件错误。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/Modern.TiddlyDev#35]
![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/32425955/64374afd-a001-4d2c-9215-e0e5dab20baa)

![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/32425955/43c34e00-f87f-41da-9eea-bcfe2af22f97)

**Comment by Zacharia2** [comment]
这是当前版本的。图中出现了两处index.css文件，而且，第一处应采用斜杠（/）,而第二处显然是重复的。

**Comment by Gk0Wk** [comment]
已修复，请升级tiddlywiki-plugin-dev v0.0.38

**Comment by Zacharia2** [comment]
OK，谢谢
