### ISSUE TITLE
在教程和仓库readme中增加使用概览

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/Modern.TiddlyDev#36]
我第一次使用的时候以为要克隆这个仓库下来再使用，没想到是使用命令，写个概览会更明确一些

**Comment by Gk0Wk** [comment]
> 我第一次使用的时候以为要克隆这个仓库下来再使用，没想到是使用命令，写个概览会更明确一些

这部分在教程里呀。你认为写到哪里更合适，可以直接上手改，然后pr过来
