### ISSUE TITLE
调试不太好用

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/Modern.TiddlyDev#37]
因为我比较菜，因此我一般比较喜欢用求值的思维玩，根据求得的结果，看看他是什么，在进行下一步，然后一步步实现它。所以没有调试真的就是臣妾做不到啊~

**Comment by Gk0Wk** [comment]
> 因为我比较菜，因此我一般比较喜欢用求值的思维玩，根据求得的结果，看看他是什么，在进行下一步，然后一步步实现它。所以没有调试真的就是臣妾做不到啊~

多用控制台：
使用浏览器的开发者工具，按 F12 键或者在浏览器菜单中选择“更多工具”>“开发者工具”

开发者工具会有一个 控制台 标签，打开会有一个聊天框一样的界面。最下方输入js代码可以执行。你输入$tw看看，该有的都有了
