### ISSUE TITLE
有什么稳定测试代码的方式呢？

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/Modern.TiddlyDev#38]
微件会因为未知代码和未知问题注册失败而没有错误提示。然后也想不到用什么方式可以稳定的，即使我写错啦也可以报错，而不是注册失败什么也没有，（果然还是我太菜了）

**Comment by oeyoews** [comment]
这个Modern.TiddlyDevv只是提供了一个TS便捷开发的环境, 并不负责这些(也负责不了)

**Comment by Zacharia2** [comment]
嗯嗯嗯，那不写widget还有那些方式可以执行JS代码呢？

**Comment by Gk0Wk** [comment]
> 微件会因为未知代码和未知问题注册失败而没有错误提示。然后也想不到用什么方式可以稳定的，即使我写错啦也可以报错，而不是注册失败什么也没有，（果然还是我太菜了）

您可以使用以下方法来测试有问题的javascript代码：
使用浏览器的开发者工具，按 F12 键或者在浏览器菜单中选择“更多工具”>“开发者工具”。
在开发者工具中，您可以使用 console.log () 方法在控制台上打印 JavaScript 值，或者使用断点、debugger 关键字等功能来调试 JavaScript 代码。
您也可以在控制台窗口直接输入或者复制粘贴要执行的 JavaScript 代码。

一般来讲出错的代码都会在开发者工具的控制台打出日志，日志中就有出错代码的位置。如果你是在开发环境，那么就会定位到对应的ts文件去。如果没有，可以用log测试法，比如你觉得某一段代码执行有问题，就可以在这段代码前面console.log(1)，其后console.log(2)，看1和2出现与否来确定问题是否出现在这个区域。
