### ISSUE TITLE
教程增加 route模块 访问本地文件内容

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/Modern.TiddlyDev#39]
备忘录：

[$:/core/modules/server/server.js](https://bramchen.github.io/tw5-docs/zh-Hans/#%24%3A%2Fcore%2Fmodules%2Fserver%2Fserver.js)

[$:/core/modules/server/routes/get-file.js](https://bramchen.github.io/tw5-docs/zh-Hans/#%24%3A%2Fcore%2Fmodules%2Fserver%2Froutes%2Fget-file.js)

这的确是用微件，但是还得配合 nodejs 那边的 router ，它们才能操作 nodejs 端的文件系统能力

在 route 里用 fs，服务端才能用fs，所以要在route里用。参考routes/get-file.js。

routes/get-file.js赋予的能力：可以直接写绝对路径访问本地文件：`http://192.168.66.21:5213/files/D:/Dropbox/21-Sandox/10-Picture/wine.png`

**Comment by Gk0Wk** [comment]
> 备忘录：
> 
> 
> 
> [$:/core/modules/server/server.js](https://bramchen.github.io/tw5-docs/zh-Hans/#%24%3A%2Fcore%2Fmodules%2Fserver%2Fserver.js)
> 
> 
> 
> [$:/core/modules/server/routes/get-file.js](https://bramchen.github.io/tw5-docs/zh-Hans/#%24%3A%2Fcore%2Fmodules%2Fserver%2Froutes%2Fget-file.js)
> 
> 
> 
> 这的确是用微件，但是还得配合 nodejs 那边的 router ，它们才能操作 nodejs 端的文件系统能力
> 
> 
> 
> 在 route 里用 fs，服务端才能用fs，所以要在route里用。

建议直接上手，添加到仓库的toturials插件中，这样别人也能看到。可以新建一个目录，比如“tw源码分析”，在里面开一个专栏

**Comment by Zacharia2** [comment]
目前还不会用route，然后route在里面调用fs
