### ISSUE TITLE
No loader is configured for 

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/Modern.TiddlyDev#44]
```
> npm run clean && tiddlywiki-plugin-dev build


> clean
> rimraf dist

Compiling...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | watch-fs✘ [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/fsevents@2.3.2/node_modules/fsevents/e

    node_modules/.pnpm/fsevents@2.3.2/node_modules/fsevents/fsevents.js:13:23:
      13 │ const Native = require("./fsevents.node");
         ╵                        ~~~~~~~~~~~~~~~~~

/Users/linonetwo/Desktop/repo/watch-fs/node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/lib/main.js:1624
  let error = new Error(`${text}${summary}`);
```

可能还是需要暴露配置文件，以便处理这类打包问题

**Comment by linonetwo** [comment]
```
  "Modern.TiddlyDev#ExternalModules": "fsevents",
```

这样可以

**Comment by linonetwo** [comment]
但是会报错

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x15b98c0?)
        runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc0000b0000?)
        sync/waitgroup.go:139 +0x52
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:177 +0x43b
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:214 +0x1ef

goroutine 18 [chan receive]:
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:110 +0x5d
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:108 +0x16b

goroutine 19 [chan receive]:
main.(*serviceType).sendRequest(0xc0000b42c0, {0x1482bc0, 0xc00034a240})
        github.com/evanw/esbuild/cmd/esbuild/service.go:203 +0xfa
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:132 +0x39
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:129 +0x26e
```

不过这可能是别的问题了

**Comment by linonetwo** [comment]
反正还是有点问题

**Comment by Gk0Wk** [comment]
> 
> 
> 但是会报错
> 
> 
> 
> ```
> 
> fatal error: all goroutines are asleep - deadlock!
> 
> 
> 
> goroutine 1 [semacquire]:
> 
> sync.runtime_Semacquire(0x15b98c0?)
> 
>         runtime/sema.go:62 +0x25
> 
> sync.(*WaitGroup).Wait(0xc0000b0000?)
> 
>         sync/waitgroup.go:139 +0x52
> 
> main.runService(0x1)
> 
>         github.com/evanw/esbuild/cmd/esbuild/service.go:177 +0x43b
> 
> main.main()
> 
>         github.com/evanw/esbuild/cmd/esbuild/main.go:214 +0x1ef
> 
> 
> 
> goroutine 18 [chan receive]:
> 
> main.runService.func1()
> 
>         github.com/evanw/esbuild/cmd/esbuild/service.go:110 +0x5d
> 
> created by main.runService
> 
>         github.com/evanw/esbuild/cmd/esbuild/service.go:108 +0x16b
> 
> 
> 
> goroutine 19 [chan receive]:
> 
> main.(*serviceType).sendRequest(0xc0000b42c0, {0x1482bc0, 0xc00034a240})
> 
>         github.com/evanw/esbuild/cmd/esbuild/service.go:203 +0xfa
> 
> main.runService.func2()
> 
>         github.com/evanw/esbuild/cmd/esbuild/service.go:132 +0x39
> 
> created by main.runService
> 
>         github.com/evanw/esbuild/cmd/esbuild/service.go:129 +0x26e
> 
> ```
> 
> 
> 
> 不过这可能是别的问题了


我和会遇到，看着是esbuild的问题，但对编译没有影响所以一直没管，这个从日志上看不出是什么问题，不太好修
