### ISSUE TITLE
为什么创建的插件会没有内容呢？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/Modern.TiddlyDev#49]
![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/109711900/77d977ce-9d65-4242-bcb5-57064a6c75ee)

使用的命令是`npm run dev`，结果如上图所示。还是说输入的命令出了问题？

**Comment by dongrentianyu** [comment]
这好像是一个幽灵问题。目前排查不出来，但主要是wiki配置中出了问题。比如可以删除掉`$__plugins_linonetwo_flow-chart.json`插件。或者其他配置。一般从cpl里安装插件是没什么问题的。

**Comment by Gk0Wk** [comment]
具体如何复现的？

**Comment by dongrentianyu** [comment]
像是因为这个问题导致的https://github.com/Jermolene/TiddlyWiki5/issues/7741

因为meta文件影响了插件更新所导致。

**Comment by dongrentianyu** [comment]
复现过程，使用命令行新建仓库。正常打开能够显示插件内容。

![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/109711900/e86d7186-af48-479a-bd39-253473bd51c9)

在太记里新建一个wiki仓库，太记版本如下。

TidGi (win32)
Version v0.8.1-prerelease6

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

把新建wiki里的tiddlers文件夹，所有条目复制到modern框架仓库的tiddlers文件夹里，重复文件点击替换原来文件。

![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/109711900/9dc8581f-8d2d-4457-8056-3554d1dd2106)

![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/109711900/879a8a0b-6b9c-417c-894d-363c793a8ceb)

创建插件。

![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/109711900/b14f27b3-9eea-42fd-91b0-a3970482cb04)


更新插件。但这一步会导致有些插件虽然更新了内容，但因为meta文件的存在，还是会提示没有更新。

![image](https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/109711900/90441ac8-9501-4247-bbee-3d60d575ed90)


但好像不会出现插件内容缺失的问题。

**Comment by dongrentianyu** [comment]
看来没有修复。问题应该是指向了`theme`类型的插件。

只要在开发插件中，选择是theme类型的，基本上都不会加载出来。

![{104C4444-3BBF-42BE-8036-A45A4B8075AB}](https://github.com/user-attachments/assets/a62763b3-3f5c-4582-8b92-02ee453b04a7)
