### ISSUE TITLE
增加模板

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/Modern.TiddlyDev#51]
可以增加一个开发的默认模板。这样开发者就不需要再重新安装那些插件了。

或者搞成可选的形式，是选择只有最必须的插件的空白版，还是有很多插件的配置开发模板。

因为自己配置的话，容易产生幽灵问题

**Comment by Gk0Wk** [comment]
可以讨论一下，有哪些可能的模板形式？

**Comment by dongrentianyu** [comment]
可以像太记一样，附带一个wiki，模板在 https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template 仓库里，不过会因为有的插件无法正常更新，而导致影响开发。

其实主要是，想添加像设拉子等库克马的一些插件，relink插件等和codemirror一类插件，感觉这些已经是tiddlywiki必备插件了，不管是搞开发还是正常写笔记。

**Comment by dongrentianyu** [comment]
当然这些模板也可以放到太记里。模板讨论当时是有一个issue来着，我找找。

https://github.com/tiddly-gittly/Awesome-TiddlyWiki-Editions

当时林一二是说在这个仓库里讨论，准备搞得像cpl一样，但后面估计没时间完成了。

**Comment by linonetwo** [comment]
初始化之后，自己用 CPL 去安装了。
