### ISSUE TITLE
Plugin Size Reduction

### ISSUE THREAD

**Issue by GameDungeon** [tiddly-gittly/Modern.TiddlyDev#52]
First, I want to say I love this tool and find it extremely useful. 

In tiddlywiki reducing plugin size is quite important, and when dealing with large libraries like my tiddly2pdf lib, a plugin can grow in size very quickly. My plugin currently sits at 1.9 MB, and that can be quite the turn-off from general use (It's bigger than some wikis.) I'm wondering if something can be done to reduce the impact large libraries have on plugin size, possible through a process like tree shaking?

**Comment by Gk0Wk** [comment]
The framework internally uses esbuild to compile the plugin , esbuild has enabled the ES6 Module Tree Shaking , and will generate the plugin js and css to minimize compression . Please check the `Modern.TiddlyDev#Minify` field.

See [doc](https://tiddly-gittly.github.io/Modern.TiddlyDev/#%24%3A%2Fplugins%2FModern.TiddlyDev%2Fdoc%2Ftutorials%2Fen%2F004-compile-config:%24%3A%2Fplugins%2FModern.TiddlyDev%2Fdoc%20%24%3A%2Fplugins%2FModern.TiddlyDev%2Fdoc%2Ftutorials%2Fen%2F004-compile-config)

**Comment by GameDungeon** [comment]
That's unfortunate then. I think that's enabled. Maybe the lib I'm using just doesn't minimize well.

**Comment by linonetwo** [comment]
Esbuild in this is upgraded, have a try on latest version.
