### ISSUE TITLE
没有使用当前项目内的tiddlywiki版本

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/Modern.TiddlyDev#54]
升级到了 5.3.2-prelease, 但是读取的时候仍然使用的是全局安装的tiddlywiki 5.3.1, 而不是当前项目安装的tiddlywiki

<img width="246" alt="image" src="https://github.com/tiddly-gittly/Modern.TiddlyDev/assets/72405338/78552040-f4e2-44a0-9013-57e0b77bca31">

**Comment by linonetwo** [comment]
用 npm 的 override 或 resolution 功能 

https://pnpm.io/package_json#pnpmoverrides
